package com.personaldata.pdmdemo.mapper;

import java.util.Set;

import org.springframework.web.multipart.MultipartFile;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

public class TableMapper {

	@DynamoDBTable(tableName = "")
    public static class ItemMapper {
	//public class ItemMapper {

		public String uuid;
		public String create_time;
		public String category;
		public String people;
		public String event_location;
		public String historical_time;
		public String description;
		public String web_link;
        public String importance;
        public String tag;
        public String priority;
		public String fileName;
		//public MultipartFile multipartFile;
		public String fileLink;  
        //public String filePath;

		// Partition key
        @DynamoDBHashKey(attributeName = "item_uuid")
        @DynamoDBAutoGeneratedKey
		public String getUuid() {
			return uuid;
		}
		public void setUuid(String uuid) {
			this.uuid = uuid;
		}
				
		@DynamoDBAttribute(attributeName = "fileName")
        public String getFileName() {
			return fileName;
		}
		public void setFileName(String fileName) {
			this.fileName = fileName;
		}
		@DynamoDBAttribute(attributeName = "fileLink")
		public String getFileLink() {
			return fileLink;
		}
		public void setFileLink(String fileLink) {
			this.fileLink = fileLink;
		}

		@DynamoDBAttribute(attributeName = "create_time")
        public String getCreate_time() {
			return create_time;
		}
		public void setCreate_time(String create_time) {
			this.create_time = create_time;
		}
		
		@DynamoDBAttribute(attributeName = "category")
		public String getCategory() {
			return category;
		}
		public void setCategory(String category) {
			this.category = category;
		}
        
		@DynamoDBAttribute(attributeName = "people")
		public String getPeople() {
			return people;
		}
		public void setPeople(String people) {
			this.people = people;
		}
		
		@DynamoDBAttribute(attributeName = "event_location")
		public String getEvent_location() {
			return event_location;
		}
		public void setEvent_location(String event_location) {
			this.event_location = event_location;
		}
		
		@DynamoDBAttribute(attributeName = "historical_time")
		public String getHistorical_time() {
			return historical_time;
		}
		public void setHistorical_time(String historical_time) {
			this.historical_time = historical_time;
		}
		
		@DynamoDBAttribute(attributeName = "description")
		public String getDescription() {
			return description;
		}
		public void setDescription(String description) {
			this.description = description;
		}
		
		@DynamoDBAttribute(attributeName = "web_link")
		public String getWeb_link() {
			return web_link;
		}
		public void setWeb_link(String web_link) {
			this.web_link = web_link;
		}

		@DynamoDBAttribute(attributeName = "importance")
		public String getImportantce() {
			return importance;
		}
		public void setImportantce(String importance) {
			this.importance = importance;
		}

		@DynamoDBAttribute(attributeName = "tag")
		public String getTag() {
			return tag;
		}
		public void setTag(String tag) {
			this.tag = tag;
		}

		/*
		 * @DynamoDBAttribute(attributeName = "priority") public String getPriority() {
		 * return priority; } public void setPriority(String priority) { this.priority =
		 * priority; }
		 */

        @Override
        public String toString() {
            return "ItemMapper [uuid=" + uuid + 
            		", create_time=" + create_time + 
            		", category=" + category + 
            		", people=" + people + 
            		", event_location=" + event_location + 
            		", historical_time=" + historical_time +
            		", description=" + description +
            		", web_link=" + web_link +
            		", importance=" + importance + 
            		", tag=" + tag + 
            		", priority=" + priority+
            		", fileName=" + fileName + 
            		", fileLink=" + fileLink + "]";
        }
		/*
		 * public MultipartFile getMultipartFile() { return multipartFile; } public void
		 * setMultipartFile(MultipartFile multipartFile) { this.multipartFile =
		 * multipartFile; }
		 */
		
		/*
		 * @DynamoDBAttribute(attributeName = "filePath") public String getFilePath() {
		 * return filePath; } public void setFilePath(String filePath) { this.filePath =
		 * filePath; }
		 */
    }
}
